### ISSUE TITLE
ontology issues

### ISSUE THREAD

**Issue by VladimirAlexiev** [EKGF/dprod#98]
Comments based on the diagram in https://github.com/EKGF/dprod/issues/94#issuecomment-2376068338:
- Why do you need new classes `Dataset, Distribution, DataService`? You can apply your props to existing classes. IMHO only `DataProduct` is needed.
  - If it's not the intent to create subclasses, then show the namespace for each class, and do something about the pink "subclass" arrows (maybe make them dashed and without arrowheads)
- why add `rdfs:label`? `dcat:Resource` uses `dct:title`

More comments:
- Maybe `informationSensitivityClassification` should be raised to `Resource` because `Distributions` might have different sensitivity?
- https://ekgf.github.io/dprod/#securityschematype shows `Range: dcat:SecuritySchemaType`. But there is no such class in `dcat`, change it to `dprod`
- Similar for https://ekgf.github.io/dprod/#protocol: there is no `dcat:Protocol`
- `dprod:Protocol` claims to be "A detailed specification, possibly including a specific version, for how to communicate with a service." but has no properties. Either elaborate or delete this class

**Comment by rivettp** [comment]
Need to include info about classes (identifier etc) as we do for properties

**Comment by jgeluk** [comment]
@rivettp just to clarify/verify, we mean here that we want to show the prefix `dcat:` in front of class names like @VladimirAlexiev mentioned in his first bullet point right? Because we do not redefine those classes in OWL, they're just referred to from some shapes...

**Comment by rivettp** [comment]
There are bugs in the SHACL that need to be fixed as mentioned: references to dcat:Protocol and dcat:SecuritySchemaType. 
OMG issue https://issues.omg.org/browse/DPROD-24 
Inclusion of class identifiers is covered by #97 
We can look at additional Protocol properties as an enhancement.

**Comment by jgeluk** [comment]
- [ ] #138 Docs/diagram: make DCAT reuse explicit; avoid implying new subclasses\n- [ ] # Shapes: fix sh:class for protocol/securitySchemaType to dprod classes\n- [ ] #139 Ontology: use rdfs:label on dprod:securitySchemaType property\n- [ ] # Modeling: review scope of informationSensitivityClassification\n- [ ] # Modeling: define or remove dprod:Protocol (properties vs URI/SKOS)\n- [ ] #140 Docs: recommend dct:title for dcat:Resource instance names; update examples\n- [ ] # Build/site: regenerate and verify published spec reflects changes

**Comment by jgeluk** [comment]
- [ ] #138 Docs/diagram: make DCAT reuse explicit; avoid implying new subclasses
- [ ] #141 Shapes: fix sh:class for protocol/securitySchemaType to dprod classes
- [ ] #139 Ontology: use rdfs:label on dprod:securitySchemaType property
- [ ] #142 Modeling: review scope of informationSensitivityClassification
- [ ] #143 Modeling: define or remove dprod:Protocol (properties vs URI/SKOS)
- [ ] #140 Docs: recommend dct:title for dcat:Resource instance names; update examples
- [ ] #144 Build/site: regenerate and verify published spec reflects changes
